"""empty message

Revision ID: 4bf858cfb719
Revises: 
Create Date: 2023-12-23 02:37:31.845995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf858cfb719'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('commodity_id', sa.String(), nullable=False),
    sa.Column('commodity_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_id'),
    sa.UniqueConstraint('product_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commodities')
    # ### end Alembic commands ###
