"""empty message

Revision ID: 5366d8ccd1e3
Revises: 4bf858cfb719
Create Date: 2023-12-23 20:44:59.227062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5366d8ccd1e3'
down_revision = '4bf858cfb719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_mcleod_status', sa.String(), nullable=True),
    sa.Column('delta_load_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delta_load_id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loads')
    # ### end Alembic commands ###
