swagger: "2.0"
info:
  title: "Delta TMS - McLeod Integration Service API"
  description: "This is an API for the service that serves as an integration between Delta TMS
   Load board and McLEod system."
  version: "1.0.0"


securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "JWT Authorization header using the Bearer scheme. Example: 'Authorization: Bearer {token}'"

#host: "api.example.com"
#basePath: "/v1"
#schemes:

tags:
  - name: "Authentication and Authorization"
    description: "Authentication and Authorization API Endpoints."
  - name: "Customers"
    description: "Customers API Endpoints"


paths:
  /auth:
    post:
      tags:
        - "Authentication and Authorization"
      summary: "Authenticate client"
      description: "Authenticate client."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Client auth request object."
          required: true
          schema:
            $ref: "#/definitions/AuthClientRequest"
      responses:
        200:
          description: "Client successfully authenticated."
          schema:
            $ref: "#/definitions/AuthClientSuccessResponse"
        400:
          description: "No username and/or password."
          schema:
            $ref: "#/definitions/FailedAuth400Response"
        404:
          description: "Authentication Failed."
          schema:
            $ref: "#/definitions/FailedAuth401Response"

  /customers:
    post:
      tags:
        - "Customers"
      security:
        - Bearer: [ ]
      summary: "Create customer"
      description: "Create new customer."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Create customer request object."
          required: true
          schema:
            $ref: "#/definitions/CreateCustomerRequest"
      responses:
        200:
          description: "Customer already exists."
          schema:
            $ref: "#/definitions/CreateCustomer200Success"
        201:
          description: "Customer successfully created."
          schema:
            $ref: "#/definitions/CreateCustomer201Success"
        400:
          description: "Create Customer Client Error."
          schema:
            $ref: "#/definitions/FailedCreateCustomer400Response"
        500:
          description: "Create Customer Server Error."
          schema:
            $ref: "#/definitions/FailedCreateCustomer500Response"

definitions:
  AuthClientRequest:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      username:
        type: "string"
        example: "GoodUser"
      password:
        type: "string"
        example: "$tr0ngPwd"

  AuthClientSuccessResponse:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Authentication Successful."
      success:
        type: "boolean"
        example: true
      access_token:
        type: "string"
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwMDQ3NTcyMiwianRpIjoiMzljNWMyNzctZTYwYi00ZmFhLTkzODgtZmUyMWUxZTQ0Nzc2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Im9icmFkb3ZpYy5pdEBnbWFpbC5jb20iLCJuYmYiOjE3MDA0NzU3MjIsImV4cCI6MTcwMDQ3NjYyMn0.xAnXS-xF6oSV8W9MGuEHGOQPJH94i024xt8HbahRudQ"

  FailedAuth400Response:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 400
      message:
        type: "string"
        example: "Please provide username and password."
      success:
        type: "boolean"
        example: false

  FailedAuth401Response:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 401
      message:
        type: "string"
        example: "Authentication failed."
      success:
        type: "boolean"
        example: false

  CreateCustomerRequest:
    type: "object"
    required:
      - "name"
      - "test"
    properties:
      name:
        type: "string"
        example: "Test Customer"
      test:
        type: "boolean"
        example: false

  CreateCustomer200Success:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 200
      message:
        type: "string"
        example: "Customer: Test Customer already exists."
      success:
        type: "boolean"
        example: true
      external_customer_id:
        type: "string"
        example: "TESCUST"

  CreateCustomer201Success:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 201
      message:
        type: "string"
        example: "Customer: Test Customer successfully saved."
      success:
        type: "boolean"
        example: true
      external_customer_id:
        type: "string"
        example: "TESCUST"

  FailedCreateCustomer400Response:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 400
      message:
        type: "string"
        example: "Please provide name for a customer."
      success:
        type: "boolean"
        example: false

  FailedCreateCustomer500Response:
    type: "object"
    properties:
      status_code:
        type: "integer"
        example: 500
      message:
        type: "string"
        example: "Unable to save customer: Test Customer"
      success:
        type: "boolean"
        example: false

